### PR TITLE
Added confirmation window

### PR DESCRIPTION
**Pull request by Loup-Garou911XD**

### CODE REVIEW

**Comment by Loup-Garou911XD** [comment]
Can you please make the window height bigger,it interferes with the discription

**Comment by Loup-Garou911XD** [comment]
Are you on discord server?
If yes then  whats your discord id?

**Comment by Loup-Garou911XD** [comment]
> Can you please make the window height bigger,it interferes with the discription 

If you do decide to do it,then `ba.rowwidget` might help ,u won't have to mess with the horizontal positioning i think

**Comment by Loup-Garou911XD** [comment]
Why the diff shows all the code 🤔

**Comment by Loup-Garou911XD** [comment]
Conflict ahhh

**Comment by kingsamurai123** [comment]
Hi Loup, I don't usually login to my account and I didn't receive the notifications about the activity on this PR, so wasn't responding. Not sure how it happened. Let's continue the discussion over there itself. So that everyone would be aware of the changes.

**Pull request merged**
